// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $page_slug_ from "./routes/page/[slug].tsx";
import * as $CardPerson from "./islands/CardPerson.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Fab from "./islands/Fab.tsx";
import * as $MovingDots from "./islands/MovingDots.tsx";
import * as $MovingNett from "./islands/MovingNett.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/page/[slug].tsx": $page_slug_,
  },
  islands: {
    "./islands/CardPerson.tsx": $CardPerson,
    "./islands/Counter.tsx": $Counter,
    "./islands/Fab.tsx": $Fab,
    "./islands/MovingDots.tsx": $MovingDots,
    "./islands/MovingNett.tsx": $MovingNett,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
